version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: checking for npm
          command: npm -v
      - run:
          name: npm
          command: npm install
      - run:
          name: Adding Android
          command: ionic cordova platform add android
      - run: 
          name: Adding iOS
          command: ionic cordova platform add ios
      - run:
          name: Print the Current Time
          command: date
