version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: checking for npm
          command: npm -v
      - run:
          name: installing ionic
          command: npm install ionic && npm install cordova && npm install && ionic cordova platform add android
